// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV36TOFAo--7DBqEWqvgHRdBHng6AhxNI',
    appId: '1:854976710498:web:e6a2f08269e8f676aace3b',
    messagingSenderId: '854976710498',
    projectId: 'ldj-dartapp',
    authDomain: 'ldj-dartapp.firebaseapp.com',
    storageBucket: 'ldj-dartapp.firebasestorage.app',
    measurementId: 'G-MM4ZZKKBJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxsPRdLrpSZFbRo5vg6LtuEMK8703w208',
    appId: '1:854976710498:android:a3935a22ecf5a26faace3b',
    messagingSenderId: '854976710498',
    projectId: 'ldj-dartapp',
    storageBucket: 'ldj-dartapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEHiXaeBkk0-_H7YS9xYcD3KkWKNdYo9s',
    appId: '1:854976710498:ios:51b9be4e4ba69715aace3b',
    messagingSenderId: '854976710498',
    projectId: 'ldj-dartapp',
    storageBucket: 'ldj-dartapp.firebasestorage.app',
    iosBundleId: 'com.example.ldjApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEHiXaeBkk0-_H7YS9xYcD3KkWKNdYo9s',
    appId: '1:854976710498:ios:51b9be4e4ba69715aace3b',
    messagingSenderId: '854976710498',
    projectId: 'ldj-dartapp',
    storageBucket: 'ldj-dartapp.firebasestorage.app',
    iosBundleId: 'com.example.ldjApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV36TOFAo--7DBqEWqvgHRdBHng6AhxNI',
    appId: '1:854976710498:web:7feaf730c70111efaace3b',
    messagingSenderId: '854976710498',
    projectId: 'ldj-dartapp',
    authDomain: 'ldj-dartapp.firebaseapp.com',
    storageBucket: 'ldj-dartapp.firebasestorage.app',
    measurementId: 'G-4D1VXN3GMJ',
  );
}
